security:
  oauth2:
    client:
      clientId: 5998769
      clientSecret: QeHq673M5Pdtl32w80du
      accessTokenUri: https://oauth.vk.com/access_token
      userAuthorizationUri: https://oauth.vk.com/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.vk.com/method/users.get